language: node_js
sudo: true
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
  - "iojs"
before_install:
  - npm install -g npm
before_script:
  - chmod -R 777 ./project/build/integration
  - npm install simple-oracledb
env:
  - DOCKER_INTEGRATION_TEST_NODE_VERSION=6
services:
  - docker
