language: node_js
sudo: true
node_js:
  - "node"
  - "8"
  - "6"
  - "4"
  - "0.12"
  - "0.10"
before_install:
  - npm install -g npm@^3
before_script:
  - chmod -R 777 ./project/build/integration
  - npm install simple-oracledb
env:
  global:
    - DOCKER_INTEGRATION_TEST_NODE_VERSION=8
services:
  - docker
